export const APP_CONFIG = {
  ASSET_VERSION: "2026-05-20-config-1",
  TILE_SIZE: 11.25,
  DEFAULT_WORLD_NEAR_CLIP: 2.5,
  DEFAULT_SHADOW_NEAR_CLIP: 0.1,
  DEFAULT_DIRECTION_ICON_SIZE: 8,
  DEFAULT_LIGHT_ANGLE: 45,
  DEFAULT_LIGHT_HEIGHT: 100,
  DEFAULT_LIGHT_INTENSITY: 1.35,
  DEFAULT_COLORS_ENABLED: true,
};
